version: "3.7"
services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:5.0.6-alpine
    expose:
      - 6379

  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend/
    ports:
      - "8000:8000"
      - "8081:443"
    stdin_open: true
    tty: true
    command: python3 ./storymanager/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis
    links:
      - db
      - redis

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend/
      - node-modules:/app/frontend/node_modules
    ports:
      - "1234:1234"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start

volumes:
  node-modules:
  postgres_data:
