# Generated by Django 2.2.5 on 2019-09-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_title', models.CharField(max_length=100)),
                ('user_cookie', models.CharField(max_length=200)),
                ('user_position', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat_at', models.DateTimeField()),
            ],
        ),
    ]
