# Generated by Django 2.2.5 on 2019-09-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='room_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='rooms.Rooms'),
        ),
    ]
