# Generated by Django 2.2.5 on 2019-09-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_texts_room_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='texts',
            old_name='room_title',
            new_name='room',
        ),
    ]
